### PR TITLE
Fix static builds for Mac OS X

### PR DESCRIPTION
**Pull request by npinchot**

### CODE REVIEW

**Comment by antialize** [comment]
I don't have mac to test this on, so i am just going to trust you.

**Comment by ashkulz** [comment]
Can you identify the specific commits which make things work, so that they can be cherry-picked to the 4.8.5 branch?

**Comment by ashkulz** [comment]
I've rebased the 4.8.6 branch on top of the latest QT 4.8 commit and included your commit earlier in the patch series (just after "make the static build for WebKit work properly").

**Comment by npinchot** [comment]
When I originally tried at a 4.8.5 build there were about a dozen or so patches, and I had to disable corewlan by manually patching the configure file. I'll try a build from wk_4.8.5 and see if I can find all the patches that are relevant.

**Comment by npinchot** [comment]
Here are all the commits I had to cherry pick in order to get a build on the wk_4.8.5 branch on OS X 10.9

952b046ba5bc99986f747729681914e21f8fb8b0
1d24a83365c2360c064563c15cb09ec8e5f6670a
4a2c688e2a0542e450a6405a74cda4762555af4f
f44310c25b372f494586dbb5b305f7e81ca63000
e2c1ff1dc18db8c786f6fa48657072ee6af7de8c
9bbe9411981a8b3fd1e6bd243a4afd3015ae9e4a
896dcd3401df5ce252050dc3315542e82769775e
08718d2e692bfa78654efd8beafc87197522dca6
98352b964f8a11751af89813c9524c35b67a5633
e3c44790065894f4e7f98ab097fce22c5bcbbd0a
ef98098ef34581a473a885badea63d415bcf64f3

Not sure why that last commit isn't auto-resolving to a link, [here it is](https://github.com/wkhtmltopdf/qt/commit/ef98098ef34581a473a885badea63d415bcf64f3).

I submitted a [pull request](https://github.com/wkhtmltopdf/qt/pull/2).

**Comment by ashkulz** [comment]
That's quite a lot of commits! Do you think it is worthwhile to backport them to wk_4.8.5 or just build off wk_4.8.6 for now?

**Comment by npinchot** [comment]
As I mentioned over on [#34 for wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf/pull/34), I'll try to see if I can cherry pick the other commits to fix 10.9, but it might be better just to ignore a 10.9 specific binary for now - time will tell :)

**Pull request merged**
