### PR TITLE
Change screen size to a more sane value

### LINKED ISSUE #20: default screen size should not be hardcoded as 800x600
should be 1280x1024

this is not 1999... (or a smart phone)

https://github.com/wkhtmltopdf/qt/commit/e673ec113aa0bd8734e0fb198e6245fcffa92fcb#diff-aa0e1e3e28d6c40d4110f7b940ae6fa6R104

### PR DESCRIPTION
**Pull request by pickworth**
closes #20

### CODE REVIEW

**Comment by ashkulz** [comment]
I think changing it to `1366x768` would be better, as that is the resolution supported by most laptops (you would get `1280x1024` on very few screens now).

**Comment by pickworth** [comment]
Cool, that would be much better, agreed - everything is pretty much 'wide screen' format these days... I've had this issue where it seems to render a websites 'mobile version' due to the screen width only being 800px.

Just out of curiosity, would you agree to can make this value read from a config file or environment variable? For me, that would be absolutely ideal, as I would ultimately prefer 1920x1080 (or at least have the ability to set it).

Please excuse my naive understanding of qt, but I understand that hard-coding 1920x1080p may cause some compatibility issues on some devices, or am I misunderstood? I mean, does the monitor and/or video adapter _really_ have to actually support the resolution? In this implementation, is it irrelevant as it is 'headless'?

Thanks,

Nathan

**Comment by ashkulz** [comment]
Squashed and merged in a5393b1f3301743c01808cd8e9aa663739309a19. Thanks!

**Comment by ashkulz** [comment]
I am not really sure about hardcoding 1920x1080, but I am open to accepting a patch which allows it to be picked up from an environment variable.

**Pull request closed without merging**
