### PR TITLE
Remove -webkit-text-size-adjust css property by backporting changeset 145168

### PR DESCRIPTION
**Pull request by poizan42**
This property would disable the effect of --zoom.
See http://webkit.org/b/56543 for discussion

### CODE REVIEW

**Comment by ashkulz** [comment]
I'm not inclined to merge this, as it would be addressed anyway after the upgrade to Qt5. Can you volunteer some time for that effort? See the [release plan](https://github.com/wkhtmltopdf/wkhtmltopdf-qt5/wiki/Release-Plan) for details.

**Comment by ashkulz** [comment]
`--zoom` is important on Windows to get proper DPI sizing, but the bug talks about `-webkit-text-size-adjust` CSS property. Also, is it required to do anything for `0.13 alpha`?

**Comment by poizan42** [comment]
You can test the behaviour with this:

```
<!DOCTYPE html>
<html>
<head><title>zoom test</title></head>
<body style="-webkit-text-size-adjust: none;">
Blah
</body>
</html>
```

Try to render it with different -zoom values.

**Comment by ashkulz** [comment]
Can you try it out, as I am not clear on what is the expected behavior?

**Comment by ashkulz** [comment]
Is this still relevant with the `0.13.x` builds? As per my knowledge, the QtWebKit snapshot is as of `r153112` so it should be fixed. If it isn't, please reopen this as an issue in the main project. Thanks for the contribution, though!

**Pull request closed without merging**
