### PR TITLE
Fix dpi

### PR DESCRIPTION
**Pull request by pvandertak**
This fixes two DPI-related bugs. The first fixes the different output scale that resulted when using different values for --dpi (due to using integer division instead of floating point division). The second fix ensures that the system DPI setting does not affect the output (due to webkit using a fixed DPI of 96 instead of the system DPI, see commit message for details).

For the second commit, I'm not sure whether hardcoding 96 there is the best solution, maybe it should include CSSHelper.h and use the constant defined in there instead. There also might be other places where qt_defaultDpi should be replaced with 96.

After these fixes, the output is consistent on Ubuntu 14.4 and Windows 8.1 regardless of the --dpi value and regardless of the windows "Make text and other items larger or smaller" setting (I tried 100%/96dpi and 150%/144dpi). My test results are in http://we.tl/PqVEjlo47g . The only difference I see is that a different font is used on windows and linux.

I also noticed that in my test case the bottom and right border should be 1mm while they are shown slightly larger. That doesn't seem to be related to these changes though (and it doesn't really bother me ;) ).

### CODE REVIEW

**Comment by ashkulz** [comment]
The first change looks good to me, but the second change effectively means that the `--dpi` switch is ignored completely. That's not something I'd like to merge right now, it might be something to do after the upgrade to Qt5 (and see if it can be supported or not)

**Comment by pvandertak** [comment]
As far as I can tell, the --dpi setting does not affect the value of qt_defaultDpi(). From what I saw, qt_defaultDpi() returns 75 on Ubuntu, 96 on Windows with default text/icon size, 120 on Windows with 125% text/icon size set in the control panel, and 144 with 150%. Using a fixed value of 96 instead of qt_defaultDpi() therefore rescales the output by a factor that is dependent on the OS settings and irrelevant of the --dpi.

You are right that the --dpi setting seems to have very little effect (also without the second patch). I only notice differences when setting it unreasonably low (e.g. --dpi 5) What exactly is it supposed to do?

**Comment by ashkulz** [comment]
Hmm, part 1 looks like it was originally report as [Webkit 40662](https://bugs.webkit.org/show_bug.cgi?id=40662) and was fixed in [r61472](http://trac.webkit.org/changeset/61472). However, when porting the patch for c1af97f5f73477f62427bdf0b6e1480b6f75b6f3 from an older WebKit version this change was effectively reverted (due to code moving around). So that will be merged going forward.

I'm still trying to see how to tweak things to get consistent rendering across platforms. If you see qt_DefaultDpi() it returns `75` in case no GUI is being used, but that code path is not used on Windows. I'll keep you updated as I test things out.

**Comment by ashkulz** [comment]
If you convert using `--zoom 1.33` on Windows, the kerning for the resultant fonts is much better. I always assumed that this was because of DPI differences (96/72 = 1.33) and even after hard-coding 72, 75 and 96 it still doesn't look as good when using old code and the above option. Until we get equally good looking fonts, I'm not really keen to merge the second part.

**Comment by pvandertak** [comment]
I see the kerning issue too, but I don't see how `--zoom 1.33` is a solution to that, since using `--zoom 1.33` makes the length units incorrect. I guess the real question is why changing the `--zoom` factor improves kerning, while increasing the `--dpi` does not have any effect on it (this is the case whether or not the second patch is used). The same happens when trying to display very thin lines. E.g. a box with width or height `<0.75 px` does not appear when `--zoom 1` is used. It does appear in higher zoom levels, but it does not appear with higher `--dpi` values. In fact, it seems like the page is always rendered with `96*zoomFactor` DPI, regardless of the `--dpi` setting. Without my change, the output would then be scaled to `96/qt_defaultDpi()` times its correct size, where `qt_defaultDpi()` depends only on the system settings (75, 96, 120, or 144 in my tests). With my change, it is scaled to the correct size. I don't think it changes anything to the kerning or quality (the only thing I see that is affected is the page size rounding, which is only noticeable for unrealistically low `--dpi`), it just makes it consistent.

I think the desired behavior would be achieved when if given `--dpi [user_dpi]`, the value for `--zoom` would multiplied by `user_dpi / 96`, and the lines in this patch would be changed to

```
    const qreal zoomFactorX = (qreal)printer->logicalDpiX() / 96 * user_dpi;
    const qreal zoomFactorY = (qreal)printer->logicalDpiY() / 96 * user_dpi;
```

but that seems like a hack to me.

**Comment by ashkulz** [comment]
In both [wkhtmltopdf.cc](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0c5e871b90bc704e9041dba41fdedcd281c25b95/src/pdf/wkhtmltopdf.cc#L136) and [wkhtmltoimage.cc](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0c5e871b90bc704e9041dba41fdedcd281c25b95/src/image/wkhtmltoimage.cc#L45) the graphics mode is initialized by default and _not changed at all for Windows_. This means that in `qt_defaultDpi` [this check is false](https://github.com/wkhtmltopdf/qt/blob/ccffd0d9842e06ed1521fa669faec2c50e6bae71/src/gui/text/qfont.cpp#L203) and the Windows DPI gets used. An easier way of achieving consistent DPI for all platforms without patching Qt is to change the `#ifdef` ordering like this:

``` diff
diff --git a/src/pdf/wkhtmltopdf.cc b/src/pdf/wkhtmltopdf.cc
index a5e8221..bfa5813 100644
--- a/src/pdf/wkhtmltopdf.cc
+++ b/src/pdf/wkhtmltopdf.cc
@@ -134,11 +134,11 @@ int main(int argc, char * argv[]) {

    //Construct QApplication required for printing
    bool use_graphics=true;
-#if defined(Q_OS_UNIX) || defined(Q_OS_MAC)
 #ifdef __EXTENSIVE_WKHTMLTOPDF_QT_HACK__
    use_graphics=globalSettings.useGraphics;
-   if (!use_graphics) QApplication::setGraphicsSystem("raster");
 #endif
+#if defined(Q_OS_UNIX) || defined(Q_OS_MAC)
+   if (!use_graphics) QApplication::setGraphicsSystem("raster");
 #endif
    QApplication a(argc, argv, use_graphics);
    MyLooksStyle * style = new MyLooksStyle();
```

However, if we're patching Qt we should ideally get better output (as I mentioned in previous comment) because all these patches will need to be ported one-by-one with the upgrade to Qt5 happening in the not-too-distant future ... and it is very easy for things to break when porting the patches so I'd prefer not to patch if possible.

I too have no clue why `--zoom` gives better kerning instead of higher DPI; at first I thought it was due to font kerning being applied at 96 DPI while internally WebKit uses 72 DPI and hence characters being too close. That's something that should be investigated ... if nothing comes up, I'd prefer to merge the changes in the above two files rather than patching Qt with a hardcoded value.

**Comment by ashkulz** [comment]
BTW, I really appreciate your contributions ... there are very few pull requests vs lots of issues reported (maybe because of the audience?) and your PRs are the kind I would love to have more of :smile:

**Comment by pvandertak** [comment]
That works for me. It does require me to use a `--zoom 0.78125` (`75/96`) to get the correct length units. It would make more sense if the `--zoom` factor would automatically be multiplied by that. As a user, I would assume that with `--zoom 1`, the length units would be correct.

I think the kerning is still not optimal with these settings though, and apart from the page size rounding, `--dpi` still does not have any effect. For me, that is not very important, as long as the length units are correct and consistent across platforms. Perhaps the future upgrade to Qt5 will solve the `--dpi` and kerning issue.

You're welcome. I really appreciate your help too (and the software itself of course)!

**Comment by ashkulz** [comment]
Can you post a test case to show why that zoom value is required (and on which platform)? Also, is the behavior affected by the `--disable-smart-shrinking` option (i.e. negating the need for the zoom value)? The `--dpi` switch has very little effect unless you use a very high value and is used by a subset of the users (see wkhtmltopdf/wkhtmltopdf#1563 and duplicates) -- it's semi-broken right now, so I'm OK with living with it. I've found that using `text-rendering: optimizeLegibility` does improve the kerning somewhat. wkhtmltopdf/wkhtmltopdf#1527 has a few examples on kerning issues which are fixed via the `--zoom` hack on Windows.

**Comment by pvandertak** [comment]
You are right, without `--zoom` and without `--disable-smart-scaling` it seems to give the correct results too. (The kerning is different, but not clearly better or worse). It is not really clear to me what `--disable-smart-scaling` is meant to do, but from this it seems that it is effectively just a `0.78125` scale factor?

My test case is here: http://we.tl/fPM4MGRB1m -- I still notice a few minor inaccuracies: the outer border (red) should be just as thick as the green border, and equally thick on all sides, but it isn't. Especially the bottom and right edges are clearly too big (and the page is not exactly the size of the red background, whereas it should be). The top and left borders seem to be slightly too thin. The differences seem to be larger than the impact I would expect from rounding, and it also happens if I try with DPI 75, 96, and a few others in an attempt to avoid rounding issues. Probably due to this, a second page is added (this did not happen before/with my patch, although the borders were not the right size there either). Also, the smaller-than-1px-boxes test in there shows incorrect results. I'm just mentioning these for the record; these are all minor things I can probably work around.

**Comment by antialize** [comment]
Qt web printing uses a smart scale algorithm, in which it tries to fit more
stuff into the same amount of pages. As I remember it will try to set the
scale to some base number (it could be 0.7), it will then try to increase
it until more pages are required. Using this algorithm makes doing anything
scale dependent very hard, this is why I made the switch to disable it.

/Jakob

**Comment by pvandertak** [comment]
Thanks for the explanation. That makes sense. So for my use case (exactly positioning elements in the page), I would want to disable it for consistent results, and I need `--zoom 0.78125` to get the correct scale (which I think should not be necessary).

**Comment by ashkulz** [comment]
Closing this as it won't be merged till a better approach is found.

**Comment by pvandertak** [comment]
What about the change in https://github.com/wkhtmltopdf/qt/pull/12#issuecomment-66224923 ? Is there any downside to that change? It at least solves the issue partially.

**Comment by ashkulz** [comment]
Well, there shouldn't be more releases in `0.12.x` so I'd prefer that focus shift to solving this for `0.13`.

**Pull request closed without merging**
