### PR TITLE
Segmentation fault fixed. Memory usage reduced during deflate compression

### PR DESCRIPTION
**Pull request by pchk**
wkhtmltopdf/wkhtmltopdf#2684

### CODE REVIEW

**Comment by ashkulz** [comment]
Some questions:
- How much was the usage before/after this patch?
- What is the technique/insight you used to ensure that lesser memory is used?
- Why do you need to grow the buffer instead of using the result of `compressBound`?

Please add a better commit message which covers all the above points.

**Comment by pchk** [comment]
Technique called "analysis". Analysed your code used for compression and found that place for optimization. 
Tested on fail.html that is attached to referenced issue. Memory consumption in critical moment reduced for about 600mb.
compressBound returns buffer size for a pessimistic scenario. In 99% cases real buffer size to fit all compressed data is 8-10x times lesser.

**Comment by pchk** [comment]
This commit fixes wkhtmltopdf/wkhtmltopdf#2684.
@ashkulz  please check it. The fix seems pretty obvious,
Tested it and it works fine (before it i had a segfault, after this fix no segfault had been occured and process finished successfully).

PS as first commit just optimizes memory usage, should i split this PR and create two PRs instead? Or you will approve this in one PR?

**Comment by ashkulz** [comment]
@pchk: looks like this is already reported upstream as [bug 68550](https://bugs.webkit.org/show_bug.cgi?id=68550) and fixed by [r95654](https://trac.webkit.org/changeset/95654). Upgrading the WebKit version used would certainly have fixed it. Please use the commit message from upstream or reference the bug and commit in a separate PR.

**Comment by ashkulz** [comment]
For the first change, please document it a bit better. e.g.

```
reduce usage from 1.2GB to 500MB during conversion for a 20kB sample HTML
```

as although you say it reduces 600MB, what was original memory usage? with which file size?

Also, instead of using `compress` multiple times, you could've used `deflateInit` and do it in an incremental manner. Also, what is the significance of `QPdfPage::chunkSize()`? Any changes from the earlier approach should be documented clearly.

**Pull request closed without merging**
