### PR TITLE
Pdf validation fixes

### PR DESCRIPTION
**Pull request by lindi2**
Fix two PDF validation issues spotted by apache preflight validator. See https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1573 for more info.

### CODE REVIEW

**Comment by ashkulz** [comment]
Looks good to me :+1: but I'd prefer it be based off `wk_4.8` -- the `wkhtmltopdf` branch was used for the import of QtWebKit 2.3 which is abandoned for now (it makes much more sense to upgrade to Qt 5.3 due to be released in April, work is happening in phantomjs for that which I hope to re-use).

Do you plan to add any more fixes? I'd prefer to merge everything at once rather than updating the QT submodule multiple times.

**Comment by lindi2** [comment]
ok, I can rebase those. I can try to take a look at the other validation issues but I can't be sure that I have time to do it.

**Comment by ashkulz** [comment]
I'm inclined to not merge the changes right now and wait till everything is done, as the validations now seem to be issues in upstream QT and may need to be submitted upstream. Also, I plan to release 0.12.1 in a week or two, right after QT 4.8.6 is released (the RC is out right now) so it would probably be merged for the release after that.

**Comment by ashkulz** [comment]
@lindi2: do I have your permission to use the explanations you have provided when trying to upstream these changes?

**Comment by lindi2** [comment]
@ashkulz sure, I wish I'd have more time to work on more issue but that depends on what other things I need to fix :)

**Comment by ashkulz** [comment]
@lindi2: I think that according to QT policy, I'll have to first submit them to QT 5 and then only it can be back-ported to QT 4.8. Considering that you don't have time to look into this immediately, I'd prefer to wait a bit -- we should hopefully migrate to QT 5 in 1-2 months time and have to do it only once :-)

**Comment by ashkulz** [comment]
Sorry, this got closed after I removed the `wkhtmltopdf` branch from the qt repository. I can't reopen it because the branch is gone...

**Pull request closed without merging**
